### PR TITLE
[IMP] Use chunked() to process pos lines in batches.

### PR DESCRIPTION
**Pull request by ivantodorovich**
@legalsylvain this, along with your current proposal, fixes https://github.com/OCA/OpenUpgrade/issues/2344
as suggested by @pedrobaeza ;)

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Hi @ivantodorovich. thanks what is the duration of the process for your 1.000.000 pos.order line ?

**Comment by ivantodorovich** [comment]
> Hi @ivantodorovich. thanks what is the duration of the process for your 1.000.000 pos.order line ?

I'll let you know when it finishes :sweat_smile: 

I'm also migrating another db with 8.000.000 lines, I'll let you know the results on that one too

**Comment by ivantodorovich** [comment]
> Hi @ivantodorovich. thanks what is the duration of the process for your 1.000.000 pos.order line ?

```
odoo_1  | 2020-06-03 10:03:03,337 517 INFO migrate odoo.modules.migration: module point_of_sale: Running migration [12.0.1.0.1>] post-migration 
odoo_1  | 2020-06-03 10:03:03,339 517 INFO migrate OpenUpgrade: point_of_sale: post-migration script called with version 11.0.1.0.1 
odoo_1  | 2020-06-03 11:12:52,643 517 DEBUG migrate OpenUpgrade: 67740 rows affected after 0:00:02.410515 running 
odoo_1  |         UPDATE pos_order po
odoo_1  |             SET amount_paid = tmp.amount_paid,
odoo_1  |             amount_return = tmp.amount_return
odoo_1  |         FROM (
odoo_1  |             SELECT
odoo_1  |                 po.id,
odoo_1  |                 sum(absl.amount) AS amount_paid,
odoo_1  |                 sum(LEAST(absl.amount, 0)) AS amount_return
odoo_1  |             FROM pos_order po
odoo_1  |             INNER JOIN account_bank_statement_line absl
odoo_1  |                 ON absl.pos_statement_id = po.id
odoo_1  |             GROUP BY po.id
odoo_1  |         ) AS tmp
odoo_1  |         WHERE po.id = tmp.id;
odoo_1  |          
odoo_1  | 2020-06-03 11:13:03,833 517 DEBUG migrate OpenUpgrade: 67749 rows affected after 0:00:11.189876 running 
odoo_1  |         UPDATE pos_order po
odoo_1  |             SET amount_total = tmp.amount_total,
odoo_1  |             amount_tax = tmp.amount_total - tmp.amount_untaxed
odoo_1  |         FROM (
odoo_1  |             SELECT
odoo_1  |                 po.id,
odoo_1  |                 sum(pol.price_subtotal_incl) AS amount_total,
odoo_1  |                 sum(pol.price_subtotal) AS amount_untaxed
odoo_1  |             FROM pos_order po
odoo_1  |             INNER JOIN pos_order_line pol
odoo_1  |                 ON pol.order_id = po.id
odoo_1  |             GROUP BY po.id
odoo_1  |         ) AS tmp
odoo_1  |         WHERE po.id = tmp.id;
odoo_1  |          
odoo_1  | 2020-06-03 11:13:03,834 517 INFO migrate OpenUpgrade: point_of_sale: loading migrations/12.0.1.0.1/noupdate_changes.xml 
```

took 1 hour for ~1.000.000 lines

**Comment by ivantodorovich** [comment]
It took 8:20 hours for ~8.500.000 lines

```
odoo_1  | 2020-06-03 10:58:04,895 525 INFO migrate OpenUpgrade: point_of_sale: post-migration script called with version 11.0.1.0.1 
odoo_1  | 2020-06-03 19:21:57,646 525 DEBUG migrate OpenUpgrade: 383866 rows affected after 0:00:17.598970 running 
```

**Comment by legalsylvain** [comment]
Makes sense !

**Pull request merged**
